import Ember from 'ember';


export const countries = Ember.A([
  {country: 'Afghanistan'                                 , iso: 'AF', iso3: 'AFG'},
  {country: 'Åland Islands'                               , iso: 'AX', iso3: 'ALA'},
  {country: 'Albania'                                     , iso: 'AL', iso3: 'ALB'},
  {country: 'Algeria'                                     , iso: 'DZ', iso3: 'DZA'},
  {country: 'American Samoa'                              , iso: 'AS', iso3: 'ASM'},
  {country: 'Andorra'                                     , iso: 'AD', iso3: 'AND'},
  {country: 'Angola'                                      , iso: 'AO', iso3: 'AGO'},
  {country: 'Anguilla'                                    , iso: 'AI', iso3: 'AIA'},
  {country: 'Antarctica'                                  , iso: 'AQ', iso3: 'ATA'},
  {country: 'Antigua and Barbuda'                         , iso: 'AG', iso3: 'ATG'},
  {country: 'Argentina'                                   , iso: 'AR', iso3: 'ARG'},
  {country: 'Armenia'                                     , iso: 'AM', iso3: 'ARM'},
  {country: 'Aruba'                                       , iso: 'AW', iso3: 'ABW'},
  {country: 'Australia'                                   , iso: 'AU', iso3: 'AUS'},
  {country: 'Austria'                                     , iso: 'AT', iso3: 'AUT'},
  {country: 'Azerbaijan'                                  , iso: 'AZ', iso3: 'AZE'},
  {country: 'Bahamas'                                     , iso: 'BS', iso3: 'BHS'},
  {country: 'Bahrain'                                     , iso: 'BH', iso3: 'BHR'},
  {country: 'Bangladesh'                                  , iso: 'BD', iso3: 'BGD'},
  {country: 'Barbados'                                    , iso: 'BB', iso3: 'BRB'},
  {country: 'Belarus'                                     , iso: 'BY', iso3: 'BLR'},
  {country: 'Belgium'                                     , iso: 'BE', iso3: 'BEL'},
  {country: 'Belize'                                      , iso: 'BZ', iso3: 'BLZ'},
  {country: 'Benin'                                       , iso: 'BJ', iso3: 'BEN'},
  {country: 'Bermuda'                                     , iso: 'BM', iso3: 'BMU'},
  {country: 'Bhutan'                                      , iso: 'BT', iso3: 'BTN'},
  {country: 'Bolivia, Plurinational State of'             , iso: 'BO', iso3: 'BOL'},
  {country: 'Bonaire, Sint Eustatius and Saba'            , iso: 'BQ', iso3: 'BES'},
  {country: 'Bosnia and Herzegovina'                      , iso: 'BA', iso3: 'BIH'},
  {country: 'Botswana'                                    , iso: 'BW', iso3: 'BWA'},
  {country: 'Bouvet Island'                               , iso: 'BV', iso3: 'BVT'},
  {country: 'Brazil'                                      , iso: 'BR', iso3: 'BRA'},
  {country: 'British Indian Ocean Territory'              , iso: 'IO', iso3: 'IOT'},
  {country: 'Brunei Darussalam'                           , iso: 'BN', iso3: 'BRN'},
  {country: 'Bulgaria'                                    , iso: 'BG', iso3: 'BGR'},
  {country: 'Burkina Faso'                                , iso: 'BF', iso3: 'BFA'},
  {country: 'Burundi'                                     , iso: 'BI', iso3: 'BDI'},
  {country: 'Cambodia'                                    , iso: 'KH', iso3: 'KHM'},
  {country: 'Cameroon'                                    , iso: 'CM', iso3: 'CMR'},
  {country: 'Canada'                                      , iso: 'CA', iso3: 'CAN'},
  {country: 'Cape Verde'                                  , iso: 'CV', iso3: 'CPV'},
  {country: 'Cayman Islands'                              , iso: 'KY', iso3: 'CYM'},
  {country: 'Central African Republic'                    , iso: 'CF', iso3: 'CAF'},
  {country: 'Chad'                                        , iso: 'TD', iso3: 'TCD'},
  {country: 'Chile'                                       , iso: 'CL', iso3: 'CHL'},
  {country: 'China'                                       , iso: 'CN', iso3: 'CHN'},
  {country: 'Christmas Island'                            , iso: 'CX', iso3: 'CXR'},
  {country: 'Cocos (Keeling) Islands'                     , iso: 'CC', iso3: 'CCK'},
  {country: 'Colombia'                                    , iso: 'CO', iso3: 'COL'},
  {country: 'Comoros'                                     , iso: 'KM', iso3: 'COM'},
  {country: 'Congo'                                       , iso: 'CG', iso3: 'COG'},
  {country: 'Congo, the Democratic Republic of the'       , iso: 'CD', iso3: 'COD'},
  {country: 'Cook Islands'                                , iso: 'CK', iso3: 'COK'},
  {country: 'Costa Rica'                                  , iso: 'CR', iso3: 'CRI'},
  {country: 'Côte d\'Ivoire'                              , iso: 'CI', iso3: 'CIV'},
  {country: 'Croatia'                                     , iso: 'HR', iso3: 'HRV'},
  {country: 'Cuba'                                        , iso: 'CU', iso3: 'CUB'},
  {country: 'Curaçao'                                     , iso: 'CW', iso3: 'CUW'},
  {country: 'Cyprus'                                      , iso: 'CY', iso3: 'CYP'},
  {country: 'Czech Republic'                              , iso: 'CZ', iso3: 'CZE'},
  {country: 'Denmark'                                     , iso: 'DK', iso3: 'DNK'},
  {country: 'Djibouti'                                    , iso: 'DJ', iso3: 'DJI'},
  {country: 'Dominica'                                    , iso: 'DM', iso3: 'DMA'},
  {country: 'Dominican Republic'                          , iso: 'DO', iso3: 'DOM'},
  {country: 'Ecuador'                                     , iso: 'EC', iso3: 'ECU'},
  {country: 'Egypt'                                       , iso: 'EG', iso3: 'EGY'},
  {country: 'El Salvador'                                 , iso: 'SV', iso3: 'SLV'},
  {country: 'Equatorial Guinea'                           , iso: 'GQ', iso3: 'GNQ'},
  {country: 'Eritrea'                                     , iso: 'ER', iso3: 'ERI'},
  {country: 'Estonia'                                     , iso: 'EE', iso3: 'EST'},
  {country: 'Ethiopia'                                    , iso: 'ET', iso3: 'ETH'},
  {country: 'Falkland Islands (Malvinas)'                 , iso: 'FK', iso3: 'FLK'},
  {country: 'Faroe Islands'                               , iso: 'FO', iso3: 'FRO'},
  {country: 'Fiji'                                        , iso: 'FJ', iso3: 'FJI'},
  {country: 'Finland'                                     , iso: 'FI', iso3: 'FIN'},
  {country: 'France'                                      , iso: 'FR', iso3: 'FRA'},
  {country: 'French Guiana'                               , iso: 'GF', iso3: 'GUF'},
  {country: 'French Polynesia'                            , iso: 'PF', iso3: 'PYF'},
  {country: 'French Southern Territories'                 , iso: 'TF', iso3: 'ATF'},
  {country: 'Gabon'                                       , iso: 'GA', iso3: 'GAB'},
  {country: 'Gambia'                                      , iso: 'GM', iso3: 'GMB'},
  {country: 'Georgia'                                     , iso: 'GE', iso3: 'GEO'},
  {country: 'Germany'                                     , iso: 'DE', iso3: 'DEU'},
  {country: 'Ghana'                                       , iso: 'GH', iso3: 'GHA'},
  {country: 'Gibraltar'                                   , iso: 'GI', iso3: 'GIB'},
  {country: 'Greece'                                      , iso: 'GR', iso3: 'GRC'},
  {country: 'Greenland'                                   , iso: 'GL', iso3: 'GRL'},
  {country: 'Grenada'                                     , iso: 'GD', iso3: 'GRD'},
  {country: 'Guadeloupe'                                  , iso: 'GP', iso3: 'GLP'},
  {country: 'Guam'                                        , iso: 'GU', iso3: 'GUM'},
  {country: 'Guatemala'                                   , iso: 'GT', iso3: 'GTM'},
  {country: 'Guernsey'                                    , iso: 'GG', iso3: 'GGY'},
  {country: 'Guinea'                                      , iso: 'GN', iso3: 'GIN'},
  {country: 'Guinea-Bissau'                               , iso: 'GW', iso3: 'GNB'},
  {country: 'Guyana'                                      , iso: 'GY', iso3: 'GUY'},
  {country: 'Haiti'                                       , iso: 'HT', iso3: 'HTI'},
  {country: 'Heard Island and McDonald Islands'           , iso: 'HM', iso3: 'HMD'},
  {country: 'Holy See (Vatican City State)'               , iso: 'VA', iso3: 'VAT'},
  {country: 'Honduras'                                    , iso: 'HN', iso3: 'HND'},
  {country: 'Hong Kong'                                   , iso: 'HK', iso3: 'HKG'},
  {country: 'Hungary'                                     , iso: 'HU', iso3: 'HUN'},
  {country: 'Iceland'                                     , iso: 'IS', iso3: 'ISL'},
  {country: 'India'                                       , iso: 'IN', iso3: 'IND'},
  {country: 'Indonesia'                                   , iso: 'ID', iso3: 'IDN'},
  {country: 'Iran, Islamic Republic of'                   , iso: 'IR', iso3: 'IRN'},
  {country: 'Iraq'                                        , iso: 'IQ', iso3: 'IRQ'},
  {country: 'Ireland'                                     , iso: 'IE', iso3: 'IRL'},
  {country: 'Isle of Man'                                 , iso: 'IM', iso3: 'IMN'},
  {country: 'Israel'                                      , iso: 'IL', iso3: 'ISR'},
  {country: 'Italy'                                       , iso: 'IT', iso3: 'ITA'},
  {country: 'Jamaica'                                     , iso: 'JM', iso3: 'JAM'},
  {country: 'Japan'                                       , iso: 'JP', iso3: 'JPN'},
  {country: 'Jersey'                                      , iso: 'JE', iso3: 'JEY'},
  {country: 'Jordan'                                      , iso: 'JO', iso3: 'JOR'},
  {country: 'Kazakhstan'                                  , iso: 'KZ', iso3: 'KAZ'},
  {country: 'Kenya'                                       , iso: 'KE', iso3: 'KEN'},
  {country: 'Kiribati'                                    , iso: 'KI', iso3: 'KIR'},
  {country: 'Korea, Democratic People\'s Republic of'     , iso: 'KP', iso3: 'PRK'},
  {country: 'Korea, Republic of'                          , iso: 'KR', iso3: 'KOR'},
  {country: 'Kuwait'                                      , iso: 'KW', iso3: 'KWT'},
  {country: 'Kyrgyzstan'                                  , iso: 'KG', iso3: 'KGZ'},
  {country: 'Lao People\'s Democratic Republic'           , iso: 'LA', iso3: 'LAO'},
  {country: 'Latvia'                                      , iso: 'LV', iso3: 'LVA'},
  {country: 'Lebanon'                                     , iso: 'LB', iso3: 'LBN'},
  {country: 'Lesotho'                                     , iso: 'LS', iso3: 'LSO'},
  {country: 'Liberia'                                     , iso: 'LR', iso3: 'LBR'},
  {country: 'Libya'                                       , iso: 'LY', iso3: 'LBY'},
  {country: 'Liechtenstein'                               , iso: 'LI', iso3: 'LIE'},
  {country: 'Lithuania'                                   , iso: 'LT', iso3: 'LTU'},
  {country: 'Luxembourg'                                  , iso: 'LU', iso3: 'LUX'},
  {country: 'Macao'                                       , iso: 'MO', iso3: 'MAC'},
  {country: 'Macedonia, the Former Yugoslav Republic of'  , iso: 'MK', iso3: 'MKD'},
  {country: 'Madagascar'                                  , iso: 'MG', iso3: 'MDG'},
  {country: 'Malawi'                                      , iso: 'MW', iso3: 'MWI'},
  {country: 'Malaysia'                                    , iso: 'MY', iso3: 'MYS'},
  {country: 'Maldives'                                    , iso: 'MV', iso3: 'MDV'},
  {country: 'Mali'                                        , iso: 'ML', iso3: 'MLI'},
  {country: 'Malta'                                       , iso: 'MT', iso3: 'MLT'},
  {country: 'Marshall Islands'                            , iso: 'MH', iso3: 'MHL'},
  {country: 'Martinique'                                  , iso: 'MQ', iso3: 'MTQ'},
  {country: 'Mauritania'                                  , iso: 'MR', iso3: 'MRT'},
  {country: 'Mauritius'                                   , iso: 'MU', iso3: 'MUS'},
  {country: 'Mayotte'                                     , iso: 'YT', iso3: 'MYT'},
  {country: 'Mexico'                                      , iso: 'MX', iso3: 'MEX'},
  {country: 'Micronesia, Federated States of'             , iso: 'FM', iso3: 'FSM'},
  {country: 'Moldova, Republic of'                        , iso: 'MD', iso3: 'MDA'},
  {country: 'Monaco'                                      , iso: 'MC', iso3: 'MCO'},
  {country: 'Mongolia'                                    , iso: 'MN', iso3: 'MNG'},
  {country: 'Montenegro'                                  , iso: 'ME', iso3: 'MNE'},
  {country: 'Montserrat'                                  , iso: 'MS', iso3: 'MSR'},
  {country: 'Morocco'                                     , iso: 'MA', iso3: 'MAR'},
  {country: 'Mozambique'                                  , iso: 'MZ', iso3: 'MOZ'},
  {country: 'Myanmar'                                     , iso: 'MM', iso3: 'MMR'},
  {country: 'Namibia'                                     , iso: 'NA', iso3: 'NAM'},
  {country: 'Nauru'                                       , iso: 'NR', iso3: 'NRU'},
  {country: 'Nepal'                                       , iso: 'NP', iso3: 'NPL'},
  {country: 'Netherlands'                                 , iso: 'NL', iso3: 'NLD'},
  {country: 'New Caledonia'                               , iso: 'NC', iso3: 'NCL'},
  {country: 'New Zealand'                                 , iso: 'NZ', iso3: 'NZL'},
  {country: 'Nicaragua'                                   , iso: 'NI', iso3: 'NIC'},
  {country: 'Niger'                                       , iso: 'NE', iso3: 'NER'},
  {country: 'Nigeria'                                     , iso: 'NG', iso3: 'NGA'},
  {country: 'Niue'                                        , iso: 'NU', iso3: 'NIU'},
  {country: 'Norfolk Island'                              , iso: 'NF', iso3: 'NFK'},
  {country: 'Northern Mariana Islands'                    , iso: 'MP', iso3: 'MNP'},
  {country: 'Norway'                                      , iso: 'NO', iso3: 'NOR'},
  {country: 'Oman'                                        , iso: 'OM', iso3: 'OMN'},
  {country: 'Pakistan'                                    , iso: 'PK', iso3: 'PAK'},
  {country: 'Palau'                                       , iso: 'PW', iso3: 'PLW'},
  {country: 'Palestine, State of'                         , iso: 'PS', iso3: 'PSE'},
  {country: 'Panama'                                      , iso: 'PA', iso3: 'PAN'},
  {country: 'Papua New Guinea'                            , iso: 'PG', iso3: 'PNG'},
  {country: 'Paraguay'                                    , iso: 'PY', iso3: 'PRY'},
  {country: 'Peru'                                        , iso: 'PE', iso3: 'PER'},
  {country: 'Philippines'                                 , iso: 'PH', iso3: 'PHL'},
  {country: 'Pitcairn'                                    , iso: 'PN', iso3: 'PCN'},
  {country: 'Poland'                                      , iso: 'PL', iso3: 'POL'},
  {country: 'Portugal'                                    , iso: 'PT', iso3: 'PRT'},
  {country: 'Puerto Rico'                                 , iso: 'PR', iso3: 'PRI'},
  {country: 'Qatar'                                       , iso: 'QA', iso3: 'QAT'},
  {country: 'Réunion'                                     , iso: 'RE', iso3: 'REU'},
  {country: 'Romania'                                     , iso: 'RO', iso3: 'ROU'},
  {country: 'Russian Federation'                          , iso: 'RU', iso3: 'RUS'},
  {country: 'Rwanda'                                      , iso: 'RW', iso3: 'RWA'},
  {country: 'Saint Barthélemy'                            , iso: 'BL', iso3: 'BLM'},
  {country: 'Saint Helena, Ascension and Tristan da Cunha', iso: 'SH', iso3: 'SHN'},
  {country: 'Saint Kitts and Nevis'                       , iso: 'KN', iso3: 'KNA'},
  {country: 'Saint Lucia'                                 , iso: 'LC', iso3: 'LCA'},
  {country: 'Saint Martin (French part)'                  , iso: 'MF', iso3: 'MAF'},
  {country: 'Saint Pierre and Miquelon'                   , iso: 'PM', iso3: 'SPM'},
  {country: 'Saint Vincent and the Grenadines'            , iso: 'VC', iso3: 'VCT'},
  {country: 'Samoa'                                       , iso: 'WS', iso3: 'WSM'},
  {country: 'San Marino'                                  , iso: 'SM', iso3: 'SMR'},
  {country: 'Sao Tome and Principe'                       , iso: 'ST', iso3: 'STP'},
  {country: 'Saudi Arabia'                                , iso: 'SA', iso3: 'SAU'},
  {country: 'Senegal'                                     , iso: 'SN', iso3: 'SEN'},
  {country: 'Serbia'                                      , iso: 'RS', iso3: 'SRB'},
  {country: 'Seychelles'                                  , iso: 'SC', iso3: 'SYC'},
  {country: 'Sierra Leone'                                , iso: 'SL', iso3: 'SLE'},
  {country: 'Singapore'                                   , iso: 'SG', iso3: 'SGP'},
  {country: 'Sint Maarten (Dutch part)'                   , iso: 'SX', iso3: 'SXM'},
  {country: 'Slovakia'                                    , iso: 'SK', iso3: 'SVK'},
  {country: 'Slovenia'                                    , iso: 'SI', iso3: 'SVN'},
  {country: 'Solomon Islands'                             , iso: 'SB', iso3: 'SLB'},
  {country: 'Somalia'                                     , iso: 'SO', iso3: 'SOM'},
  {country: 'South Africa'                                , iso: 'ZA', iso3: 'ZAF'},
  {country: 'South Georgia and the South Sandwich Islands', iso: 'GS', iso3: 'SGS'},
  {country: 'South Sudan'                                 , iso: 'SS', iso3: 'SSD'},
  {country: 'Spain'                                       , iso: 'ES', iso3: 'ESP'},
  {country: 'Sri Lanka'                                   , iso: 'LK', iso3: 'LKA'},
  {country: 'Sudan'                                       , iso: 'SD', iso3: 'SDN'},
  {country: 'Suriname'                                    , iso: 'SR', iso3: 'SUR'},
  {country: 'Svalbard and Jan Mayen'                      , iso: 'SJ', iso3: 'SJM'},
  {country: 'Swaziland'                                   , iso: 'SZ', iso3: 'SWZ'},
  {country: 'Sweden'                                      , iso: 'SE', iso3: 'SWE'},
  {country: 'Switzerland'                                 , iso: 'CH', iso3: 'CHE'},
  {country: 'Syrian Arab Republic'                        , iso: 'SY', iso3: 'SYR'},
  {country: 'Taiwan, Province of China'                   , iso: 'TW', iso3: 'TWN'},
  {country: 'Tajikistan'                                  , iso: 'TJ', iso3: 'TJK'},
  {country: 'Tanzania, United Republic of'                , iso: 'TZ', iso3: 'TZA'},
  {country: 'Thailand'                                    , iso: 'TH', iso3: 'THA'},
  {country: 'Timor-Leste'                                 , iso: 'TL', iso3: 'TLS'},
  {country: 'Togo'                                        , iso: 'TG', iso3: 'TGO'},
  {country: 'Tokelau'                                     , iso: 'TK', iso3: 'TKL'},
  {country: 'Tonga'                                       , iso: 'TO', iso3: 'TON'},
  {country: 'Trinidad and Tobago'                         , iso: 'TT', iso3: 'TTO'},
  {country: 'Tunisia'                                     , iso: 'TN', iso3: 'TUN'},
  {country: 'Turkey'                                      , iso: 'TR', iso3: 'TUR'},
  {country: 'Turkmenistan'                                , iso: 'TM', iso3: 'TKM'},
  {country: 'Turks and Caicos Islands'                    , iso: 'TC', iso3: 'TCA'},
  {country: 'Tuvalu'                                      , iso: 'TV', iso3: 'TUV'},
  {country: 'Uganda'                                      , iso: 'UG', iso3: 'UGA'},
  {country: 'Ukraine'                                     , iso: 'UA', iso3: 'UKR'},
  {country: 'United Arab Emirates'                        , iso: 'AE', iso3: 'ARE'},
  {country: 'United Kingdom'                              , iso: 'GB', iso3: 'GBR'},
  {country: 'United States'                               , iso: 'US', iso3: 'USA'},
  {country: 'United States Minor Outlying Islands'        , iso: 'UM', iso3: 'UMI'},
  {country: 'Uruguay'                                     , iso: 'UY', iso3: 'URY'},
  {country: 'Uzbekistan'                                  , iso: 'UZ', iso3: 'UZB'},
  {country: 'Vanuatu'                                     , iso: 'VU', iso3: 'VUT'},
  {country: 'Venezuela, Bolivarian Republic of'           , iso: 'VE', iso3: 'VEN'},
  {country: 'Viet Nam'                                    , iso: 'VN', iso3: 'VNM'},
  {country: 'Virgin Islands, British'                     , iso: 'VG', iso3: 'VGB'},
  {country: 'Virgin Islands, U.S.'                        , iso: 'VI', iso3: 'VIR'},
  {country: 'Wallis and Futuna'                           , iso: 'WF', iso3: 'WLF'},
  {country: 'Western Sahara'                              , iso: 'EH', iso3: 'ESH'},
  {country: 'Yemen'                                       , iso: 'YE', iso3: 'YEM'},
  {country: 'Zambia'                                      , iso: 'ZM', iso3: 'ZMB'},
  {country: 'Zimbabwe'                                    , iso: 'ZW', iso3: 'ZWE'}
]);


export const countriesWithoutZip = Ember.A([
  'AG', 'AW', 'BS', 'BZ', 'BJ', 'BQ',
  'BW', 'BF', 'BI', 'CF', 'KM', 'CG',
  'CD', 'CK', 'CI', 'CW', 'DJ', 'DM',
  'TL', 'GQ', 'ER', 'FJ', 'TF', 'GM',
  'GH', 'GD', 'GN', 'GY', 'HK', 'IE',
  'KI', 'KP', 'MO', 'MW', 'ML', 'MR',
  'MU', 'NR', 'NU', 'QA', 'KN', 'LC',
  'ST', 'SC', 'SX', 'SL', 'SB', 'SO',
  'SR', 'SY', 'TZ', 'TG', 'TK', 'TO',
  'TV', 'UG', 'AE', 'VU', 'YE', 'ZW'
]);


export const countriesWithState = Ember.A(["US", "CA"]);
